language: go
sudo: false

go:
  - 1.1.2
  - 1.2.2
  - 1.3.3
  - 1.4.3
  - 1.5.4
  - 1.6.4
  - 1.7.5
  - 1.8
  - master

matrix:
  include:
  - go: 1.8
    env: TEST_REAL_SERVER=rackspace
  - go: 1.8
    env: TEST_REAL_SERVER=memset
  allow_failures:
  - go: 1.8
    env: TEST_REAL_SERVER=rackspace
  - go: 1.8
    env: TEST_REAL_SERVER=memset
before_install:
  - mkdir -p $GOPATH/src/github.com/ncw
  - cp -a ../swift $GOPATH/src/github.com/ncw/
  - cd $GOPATH/src/github.com/ncw/swift
install: go test -i ./...
script:
  - test -z "$(go fmt ./...)"
  - go test
  - ./travis_realserver.sh
